// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerstaTask.Models;

#nullable disable

namespace VerstaTask.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260920141002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("VerstaTask.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdressReceiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdressSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityReceiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitySender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
