// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VestaTask.Models;

#nullable disable

namespace VestaTask.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260920150354_AdjustNaming")]
    partial class AdjustNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("VestaTask.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressReceiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityReceiver")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitySender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PickDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
